elite-kings-county-ledger-dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 4
      account: "{{ env_var('account') }}"
      database: "{{ env_var('database') }}"
      user: "{{ env_var('user') }}"
      password: "{{ env_var('ELITE_KINGS_COUNTY_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('role') }}"
      schema: "{{ env_var('schema') }}"
      warehouse: "{{ env_var('warehouse') }}"
