name: CI pipeline

on:
  pull_request:
    paths:
      - "dbt/**"
      - "requirements.txt"

jobs:
  lint:
    name: SQLFluff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run SQLFluff lint
        run: sqlfluff lint dbt/models/
