name: CI pipeline

on:
  pull_request:
    paths:
      - "**.sql"
      - "dbt_project/**"

jobs:
  lint:
    name: SQLFluff Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt

      - name: Run SQLFluff lint
        run: sqlfluff lint dbt_project/models/
